//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRoleTesting
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageRoles
    {
        public int Id { get; set; }
        public int PageId { get; set; }
        public int RoleId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Pages Pages { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
